[package]
name = "sorting"
version = "0.1.0"
authors = ["Rust & Python <nexinov@localhost.gud-o15>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
